# -*- coding: utf-8 -*-
"""Day 27ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpqeeqJqxB9TYhvi0trQ-MoHEFL_Dn6I
"""

//Predict whether a student will get placed or not based on:

CGPA

IQ

Profile Score / Internship Score

Binary Classification Problem (0 = Not Placed, 1 = Placed)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

data = {
    'cgpa': [6,7,8,9,5,4,8,7,6,9],
    'iq': [110,120,130,140,100,90,125,115,105,150],
    'profile_score': [5,6,7,9,4,3,8,6,5,10],
    'placed': [0,1,1,1,0,0,1,1,0,1]
}

df = pd.DataFrame(data)
df

X = df[['cgpa', 'iq', 'profile_score']]
y = df['placed']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

new_student = [[8.5, 135, 8]]
print("Prediction:", model.predict(new_student))